### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by litangyu** [JayFang1993/AlipayAR#2]
localhost:alipayAR lty$ python alipayAR.py input/ output/
Traceback (most recent call last):
  File "alipayAR.py", line 72, in <module>
    input()
  File "alipayAR.py", line 67, in input
    handlerImg(path,path2)
  File "alipayAR.py", line 17, in handlerImg
    w=im.width
  File "/Library/Python/2.7/site-packages/PIL/Image.py", line 512, in __getattr__
    raise AttributeError(name)
AttributeError: width

**Comment by JayFang1993** [comment]
这应该是加载图片出错了，看看你的图片路径有没有问题，或者看你的PIL库安装的对不对

**Comment by litangyu** [comment]
好的
